#!/bin/bash
#youtube-mp3 install script

function installformac() {
  brew install ffmpeg # use brew install
  sudo mv libavcodec.52.dylib /usr/local/bin/libavcodec.dylib
  sudo mv libavformat.52.dylib /usr/local/bin/libavformat.dylib
  sudo mv libavutil.50.dylib /usr/local/bin/libavutil.dylib
  sudo mv libswscale.0.dylib /usr/local/bin/libswscale.dylib
  sudo rm -rf /tmp/ffmpeg.zip
  sudo rm -rf /tmp/FFmpeg_*
  sudo cp ./youtube-dl-8-30 /usr/local/bin/youtube-dl
  sudo curl --output /usr/local/bin/youtube-mp3 https://raw.github.com/dejay/youtube-mp3/master/youtube-mp3
  sudo chmod a+x /usr/local/bin/youtube-dl
  sudo chmod a+x /usr/local/bin/youtube-mp3
}

function installforlinux() {
  sudo cp ./youtube-dl-8-31 --output-document=/usr/local/bin/youtube-dl
  sudo wget --output-document=/usr/local/bin/youtube-mp3 https://raw.github.com/dejay/youtube-mp3/master/youtube-mp3
  sudo chmod a+x /usr/local/bin/youtube-dl
  sudo chmod a+x /usr/local/bin/youtube-mp3
}

function finished() {
  echo
  echo finis!
  echo
}

if [ "$(uname -s)" != "Darwin" ]; then
  installforlinux
  finished
elif [ "$(uname -s)" = "Darwin" ]; then
  installformac
  finished
fi

